### ISSUE TITLE
Is this symbol-library sub-repo replacing the standalone symbol-library repo?

### ISSUE THREAD

**Issue by cboone** [nationalparkservice/npmap5-plugins#4]
Is this sub-repo https://github.com/nationalparkservice/npmap5-plugins/tree/main/symbol-library replacing the standalone https://github.com/nationalparkservice/symbol-library?

Thanks!

**Comment by jimmyrocks** [comment]
The new NPMap5 symbol library is intended to replace the standalone library.
The plan is to remove all the "shielded" icons, since they can now be generated on the fly in the browser. We also are moving from including all 14px and 22px icon sizes and only including new icons where there is a difference in the two.

This is mostly an effort to reduce the size, and now we're using typescript and SVGO in our build process.
